services:
  - type: web
    name: finance-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js

  - type: web
    name: finance-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
